# Generated by Django 3.2.12 on 2022-05-26 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.IntegerField(primary_key=True, serialize=False)),
                ('genre_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GenreSort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('overview', models.TextField(null=True)),
                ('en_overview', models.TextField(null=True)),
                ('release_date', models.DateField()),
                ('runtime', models.IntegerField()),
                ('poster_path', models.TextField()),
                ('original_title', models.CharField(max_length=100)),
                ('original_language', models.CharField(max_length=100)),
                ('vote_count', models.IntegerField()),
                ('vote_average', models.FloatField()),
                ('imdb_id', models.CharField(max_length=10, null=True)),
                ('genres', models.ManyToManyField(related_name='movies', to='movies.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('provider_id', models.IntegerField(primary_key=True, serialize=False)),
                ('provider_name', models.CharField(max_length=30)),
                ('owned_movies', models.ManyToManyField(related_name='OTTs', to='movies.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='MovieImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_URL', models.CharField(max_length=500)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
        ),
        migrations.AddField(
            model_name='genre',
            name='genre_sort',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genres', to='movies.genresort'),
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('director_id', models.IntegerField(primary_key=True, serialize=False)),
                ('gender', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=100)),
                ('biography', models.TextField(null=True)),
                ('imdb_id', models.CharField(max_length=100, null=True)),
                ('profile_path', models.CharField(max_length=500, null=True)),
                ('popularity', models.FloatField(default=0)),
                ('filmographies', models.ManyToManyField(related_name='directors', to='movies.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('actor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('gender', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=100)),
                ('biography', models.TextField(null=True)),
                ('imdb_id', models.CharField(max_length=100, null=True)),
                ('profile_path', models.CharField(max_length=500, null=True)),
                ('popularity', models.FloatField(default=0)),
                ('filmographies', models.ManyToManyField(related_name='actors', to='movies.Movie')),
            ],
        ),
    ]
